import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "metablog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0c0512] tracking-tight overscroll-none font-sans">
        <div className="mb-[88px] sm:mb-24 md:mb-28">
          <Header />
        </div>
        <div className="z-40">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
